#!/bin/bash

function dotfu() {
  # Local vars
  local -r command=$1
  shift

  local -r install_dir=${DOTFILES_INSTALL_DIR:-~}
  local command_list=()
  local is_dryrun=false

  # Guard clauses
  if [[ -z $command ]] ; then
    >&2 echo "Error: no command provided."
    return 1
  fi

  if [[ -z $DOTFILES_DIR ]] && [[ $command != "bootstrap" ]] ; then
    >&2 echo "Error: environment variable DOTFILES_DIR has not been set."
    return 1
  fi

  # Local functions
  function translate_path() {
    echo $1                    |
    sed -r 's|/_([^_])|/.\1|g' |
    sed -r 's|^_([^_])|.\1|'   |
    sed 's|/__|/_|g'           |
    sed 's|^__|_|'
  }

  function extension() {
    echo "${1##*.}"
  }

  function filename() {
    local -r base=$(basename -- $1)
    echo "${base}"
  }

  function run_command() {
    local -r command=$1
    shift

    for i in "${command_list[@]}" ; do
      if [[ "$command" == "$i" ]] ; then
        eval "df_${command} ${@}"
        return 0
      fi
    done

    echo "Error: ${command} is not a valid command."
    echo "Commands: ${command_list[*]}"
    return 1
  }

  # Commands
  command_list+=("cd")
  function df_cd() {
    cd $DOTFILES_DIR
  }

  command_list+=("status")
  function df_status() {
    (cd $DOTFILES_DIR && git status)
  }

  command_list+=("translate")
  function df_translate() {
    translate_path $1
  }

  command_list+=("install")
  function df_install() {
    ## Local vars
    local -r module=$1
    shift

    local -r module_dir="${DOTFILES_DIR}/${module}"

    ## Guard clauses
    if [[ -z $module ]] ; then
      >&2 echo "Error: no module provided."
      return 1
    fi

    if [[ ! -d "$module_dir" ]] ; then
      >&2 echo "Error: cannot find '${module_dir}'."
      return 1
    fi

    ## Local functions
    function is_post_install_item() {
      local -r name=$(filename $1)
      [[ "$name" == "post_install.dotfu" ]]
    }

    function is_dotfu_item() {
      local -r ext=$(extension $1)
      [[ "$ext" == "dotfu" ]]
    }

    function src_to_dest() {
      local -r src=$1
      local -r rel_src=${src#"${module_dir}/"}
      local -r rel_dest=$(translate_path $rel_src)
      echo "${install_dir}/${rel_dest}"
    }

    function process_item() {
      local -r src=$1
      local -r dest=$(src_to_dest $src)

      function remove_existing() {
        if [[ -e $1 || -L $1 ]] ; then
          >&2 echo "remove : ${1}"
          [[ "$is_dryrun" == false ]] && rm -rf $1
        fi
      }

      function install_file() {
        remove_existing $dest
        >&2 echo "link   : ${dest} -> ${src}"
        [[ "$is_dryrun" == false ]] && ln -s $src $dest
      }

      function install_dir() {
        [[ -d $dest ]] && return 0

        remove_existing $dest
        >&2 echo "create : ${dest}"
        [[ "$is_dryrun" == false ]] && mkdir $dest
      }

      function install_symlink() {
        local -r target_in_dotfiles_dir=$(readlink $src)
        if [[ "$target_in_dotfiles_dir" =~ ^/ ]] ; then
          >&2 echo "Error: ${src} is a link with an absolute pad ${target_in_dotfiles_dir}, which is not supported. Skipping."
          return 1
        fi

        local -r target_in_install_dir=$(translate_path $target_in_dotfiles_dir)
        [[ -d $src && -d $dest ]] || remove_existing $dest
        >&2 echo "link   : ${dest} -> ${target_in_install_dir}"
        [[ "$is_dryrun" == false ]] && ln -s $target_in_install_dir $dest
      }

      # Test for links needs to happen first.
      if [[ -L $src ]] ; then
        install_symlink
      elif [[ -d $src ]] ; then
        install_dir
      elif [[ -f $src ]] ; then
        install_file
      fi
    }

    ## Main
    >&2 echo "Installing ${module} (using DOTFILE_INSTALL_DIR='${install_dir}')"
    local -r items=( $(find "${module_dir}" -print) )
    for i in "${items[@]}" ; do
      [[ ${i} == "${module_dir}" ]] && continue
      is_dotfu_item $i && continue
      process_item $i
    done

    for i in "${items[@]}" ; do
      if is_post_install_item $i ; then
        local work_dir=$(dirname $(src_to_dest $i))
        >&2 echo "sourcing ${i} (with pwd=${work_dir})."
        [[ "$is_dryrun" == false ]] && (cd $work_dir && source $i)
      fi
    done
  }

  command_list+=("dryrun")
  function df_dryrun() {
    is_dryrun=true
    run_command $@
  }

  # Main
  run_command $command $@
}

dotfu $@
